dependencies:
  - name: certificateapi
    version: 0.1.0
    condition: certificateapi.enabled
  - name: certificatesign
    version: 0.1.0
    condition: certificatesign.enabled
  - name: claim-ms
    version: 0.1.0
    condition: claim-ms.enabled
  - name: elasticsearch
    version: 7.3.2
    condition: elasticsearch.enabled
  - name: filestorage
    version: 0.1.0
    condition: filestorage.enabled
  - name: keycloak
    version: 0.1.0
    condition: keycloak.enabled
  - name: registry
    version: 0.1.0
    condition: registry.enabled